---

- gather_facts: no
  hosts: all
  connection: local 
  tasks:
    - name: include host variables
      include_vars: 
        file: "{{host_variable_file}}"
        name: ok_vars

    - name: display host_id variable
      ansible.builtin.debug:
        var: host_id

    # - name: fail
    #   ansible.builtin.fail:
    #     msg: "force failure"

    # - name: display ok_vars for host
    #   ansible.builtin.debug:
    #     var: ok_vars

    # extend me...